// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone.GoogleChart = (function(_super) {
    __extends(GoogleChart, _super);

    function GoogleChart() {
      this.listen = __bind(this.listen, this);
      this.render = __bind(this.render, this);
      this.id = __bind(this.id, this);      _ref = GoogleChart.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    # Initialize a new GoogleChart object
    # In addition to the default Backbone.View options ( such as id, className etc...)
    # Google.ChartWrapper#options should also be passed using the `chartOptions` key
    #
    # Example:
    #   options = {
    #     chartType: 'ColumnChart',
    #     dataTable: [['Germany', 'USA', 'Brazil', 'Canada', 'France', 'RU'],
    #                [700, 300, 400, 500, 600, 800]],
    #     options: {'title': 'Countries'},
    #   }
    #
    #   graph = new Backbone.GoogleChart({chartOptions: options});
    #
    #   $('body').append( graph.render().el );
    # 
    # For the complete list of options that can be passed through the `chartOptions` attribute
    # https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject
    #
    # Please don't try to pass `containerId`, it will be ignored, instead use the `id` attribute, e.g
    #   graph = new Backbone.GoogleChart({chartOptions: options, id:"MyCustomID"});
    #
    */


    GoogleChart.prototype.initialize = function(options) {
      var _this = this;

      return google.load('visualization', '1', {
        packages: ['corechart'],
        callback: function() {
          (options.chartOptions != null) || (function() {
            throw "chartOptions is missing";
          })();
          delete options.chartOptions.containerId;
          _this.google = google.visualization;
          _this.wrapper = new _this.google.ChartWrapper(options.chartOptions);
          return ['ready', 'select', 'error'].map(_this.listen);
        }
      });
    };

    /*
    # Execute a callback once a given element ID appears in DOM ( mini livequery ).
    #
    # We need it because GoogleChart object only draw itself on DOM elements
    # so we first need to wait for our element to be added to the DOM before
    # we call GoogleChart.draw().
    # 
    # Usage: 
    #   Backbone.GoogleChart.watch("#myid", function() { console.log("I'm in") });
    #   $("body").append("<div id='myid'></div>"); // 'I"m in' should be printed to console
    #
    */


    GoogleChart.watch = function(id, fn) {
      var func;

      (GoogleChart._list || (GoogleChart._list = {}))[id] = fn;
      if (GoogleChart._watching) {
        return;
      }
      GoogleChart._watching = true;
      func = function() {
        return _(GoogleChart._list).map(function(fn, id) {
          if ($(id)[0]) {
            fn() || delete GoogleChart._list[id];
          }
          if (_(GoogleChart._list).isEmpty()) {
            return GoogleChart._watching = false;
          } else {
            return setTimeout(func, 20);
          }
        });
      };
      return setTimeout(func, 20);
    };

    /*
    # Returns the wrapping element id
    # if no id was specified on initialization a random one will be returned
    */


    GoogleChart.prototype.id = function() {
      var _ref1;

      return ((_ref1 = this.el) != null ? _ref1.id : void 0) || this.randomID();
    };

    /*
    # "Instruct" the current graph instance to draw itself once its visiable on DOM
    # return the current instance
    */


    GoogleChart.prototype.render = function() {
      var _this = this;

      this.constructor.watch("#" + this.el.id, function() {
        return _this.wrapper.draw(_this.el.id);
      });
      return this;
    };

    /*
    # Register for ChartWrapper events
    # For the complete event list please look at the events section under
    #  https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject
    # 
    # By default the ready, select and error events are register automatically on initialization
    # so instead of calling this function directly consider this:
    #   graph = new Backbone.GoogleChart({chartOptions: options});
    #   graph.on("select",function(graph) { console.log("Someone click on me!") })
    #   graph.on("error",function(graph) { console.log("Oops") })
    #   graph.on("ready",function(graph) { console.log("I'm ready!") })
    #
    */


    GoogleChart.prototype.listen = function(event) {
      var _this = this;

      return this.google.events.addListener(this.wrapper, event, function() {
        return _this.trigger(event, _this.wrapper.getChart());
      });
    };

    /*
    # Generate a random ID, gc_XXX
    */


    GoogleChart.prototype.randomID = function() {
      return _.uniqueId("gc_");
    };

    return GoogleChart;

  }).call(this, Backbone.View);

}).call(this);
